-- Items de démarrage (facultatif) pour un mariage catholique.
-- À exécuter dans Supabase > SQL Editor APRÈS supabase-schema.sql.
-- Il en faut au moins 25 pour générer une grille — en voici ~35.

insert into items (text, added_by) values
  ('Tata pleure pendant la messe', 'Ringo'),
  ('Le curé fait une blague', 'Ringo'),
  ('Un bébé pleure pendant l''homélie', 'Ringo'),
  ('Quelqu''un se trompe dans les paroles du chant', 'Ringo'),
  ('La mariée pleure en disant oui', 'Ringo'),
  ('Un téléphone sonne pendant la cérémonie', 'Ringo'),
  ('Quelqu''un arrive en retard à l''église', 'Ringo'),
  ('On chante « Je vous salue Marie »', 'Ringo'),
  ('Les alliances sont presque oubliées', 'Ringo'),
  ('Quelqu''un renverse un verre de vin', 'Ringo'),
  ('Un enfant d''honneur fait une bêtise', 'Ringo'),
  ('Discours qui dure trop longtemps', 'Ringo'),
  ('Quelqu''un pleure pendant un discours', 'Ringo'),
  ('La pièce montée est un choux à la crème', 'Ringo'),
  ('Première danse des mariés', 'Ringo'),
  ('Tonton fait le kéké sur la piste', 'Ringo'),
  ('On lance le bouquet', 'Ringo'),
  ('Quelqu''un attrape le bouquet et rougit', 'Ringo'),
  ('Un invité s''endort à table', 'Ringo'),
  ('Quelqu''un parle du « prochain mariage »', 'Ringo'),
  ('Selfie avec les mariés', 'Ringo'),
  ('Un drone ou un photographe très présent', 'Ringo'),
  ('On trinque « aux mariés ! »', 'Ringo'),
  ('Quelqu''un demande « c''est pour quand les enfants ? »', 'Ringo'),
  ('Le DJ passe un slow des années 80', 'Ringo'),
  ('Grand-mère danse', 'Ringo'),
  ('Quelqu''un perd une chaussure sur la piste', 'Ringo'),
  ('Un toast en latin ou en anglais', 'Ringo'),
  ('Les mariés se font porter en triomphe', 'Ringo'),
  ('Quelqu''un a un peu trop bu', 'Ringo'),
  ('Photo de groupe interminable', 'Ringo'),
  ('On entonne « Ils s''aiment » de Debout sur le Zinc', 'Ringo'),
  ('Un couple se forme pendant la soirée', 'Ringo'),
  ('Quelqu''un parle du sermon à l''apéro', 'Ringo'),
  ('Feu d''artifice ou étincelles', 'Ringo');
